version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=logger_api
      - POSTGRES_DB=logger_api
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/tables.sql:/docker-entrypoint-initdb.d/1-tables.sql
      - ./postgres/import.sql:/docker-entrypoint-initdb.d/2-import.sql
      - ./postgres/users.csv:/data/users.csv


networks:
  default:
    driver: bridge