{
 "title": "Immudb",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "S3 statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "immudb_remoteapp_open_time",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(immudb_remoteapp_open_time_bucket{job=\"immudbsvc\"}) by (pod, le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "S3 I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "rate(immudb_remoteapp_read_bytes{job=\"immudbsvc\"}[$__rate_interval])",
       "legendFormat": "S3 read {{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Database size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(immudb_db_size_bytes{job=\"immudbsvc\"}) by (db)",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Database growth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(immudb_db_size_bytes{job=\"immudbsvc\"}[$__rate_interval])) by (db)",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Stored Entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(immudb_number_of_stored_entries{job=\"immudbsvc\"}) by (db)",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Stored Entries rate by Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(immudb_number_of_stored_entries{job=\"immudbsvc\"}[$__rate_interval])*60) by (db)",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Uptime in hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(immudb_db_size_bytes{job=\"immudbsvc\"}) by (db)",
     "legendFormat": "{{db}}"
    }
   ]
  },
  { "title": "Internal stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Indexed %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "immudb_last_indexed_trx_id/immudb_last_committed_trx_id",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Indexing / commit rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "rate(immudb_last_indexed_trx_id[$__rate_interval])",
     "legendFormat": "Idx {{db}}"
    },
    {
     "expr": "rate(immudb_last_committed_trx_id{db=~\"lc.*\"}[$__rate_interval])",
     "legendFormat": "Cmt {{db}}"
    }
   ]
  },
  {
   "title": "TRXs left to index",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "immudb_last_committed_trx_id-immudb_last_indexed_trx_id",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "TRX count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    { "expr": "immudb_last_committed_trx_id", "legendFormat": "{{db}}" }
   ]
  },
  {
   "title": "Btree cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    { "expr": "immudb_btree_cache_size\n", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Btree depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    { "expr": "immudb_btree_depth\n", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Btree flushed entries last cycle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "immudb_btree_flushed_entries_last_cycle\n",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Btree flushed nodes last cycle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "immudb_btree_flushed_nodes_last_cycle\n",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "BTree cache hit%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(immudb_btree_cache_hit[$__rate_interval]) /\n(\n    rate(immudb_btree_cache_miss[$__rate_interval])+\n    rate(immudb_btree_cache_hit[$__rate_interval])\n)\n",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}